import type { Metadata } from "next";
import { Gabarito } from "next/font/google";
import "./globals.css";
import NavigationBar from "./components/NavBar";

export const metadata: Metadata = {
  title: "Kusuma Resume",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavigationBar />
        {children}
      </body>
    </html>
  );
}
